query GetUserProfile($userId: String!) {
  userProfile(userId: $userId) {
    userId
    email
    userType
    selectedTab
    firstName
    lastName
    companyName
    nip
    selectedCountry
    streetAndNumber
    apartmentUnit
    postalCode
    city
    regionState
    phoneNumber
    createdAt
    updatedAt
  }
}
